name: ez_flutter
version: 1.3.0+25
publish_to: none
description: Your fin buddy.
environment: 
  sdk: '>=2.16.1 <3.0.0'
dependencies: 
  blobs: ^2.0.0
  camera: ^0.10.5
  charts_flutter_new: ^0.12.0
  cloud_firestore: ^4.5.0
  cloud_functions: ^4.0.12
  connectivity_plus: ^3.0.3
  dartz: ^0.10.1
  dio: ^5.0.0
  feather_icons: ^1.2.0
  file_picker: ^4.5.1
  firebase_core: ^2.7.0
  flutter_bloc: ^8.1.2
  flutter_image_compress: ^1.1.0
  flutter_secure_storage: ^8.0.0
  flutter_share: ^2.0.0
  flutter_svg: ^1.0.3
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  http: ^0.13.4
  image_picker: ^0.8.5+3
  injectable: ^2.1.0
  intl: ^0.17.0
  lottie: ^2.3.1
  onesignal_flutter: ^3.2.8
  open_file: ^3.2.1
  otp_text_field: ^1.1.2
  package_info_plus: ^1.3.0
  path: ^1.8.0
  path_provider: ^2.0.8
  permission_handler: ^10.2.0
  pinput: ^2.2.21
  qr_flutter: ^4.0.0
  share_plus: ^4.5.3
  shimmer: ^2.0.0
  store_redirect: ^2.0.1
  universal_io: ^2.0.4
  url_launcher: ^6.1.10
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
dev_dependencies: 
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.4
  json_serializable: ^6.1.4
  pubspec_dependency_sorter: ^1.0.3
  flutter_test: 
    sdk: flutter
flutter: 
  assets: 
    - assets/images/
    - assets/icons/
    - assets/lottie/
  uses-material-design: true
flutter_icons: 
  android: launcher_icon
  ios: AppIcon
  image_path: assets/images/googleplayicon-ed.jpg
  remove_alpha_ios: true
