// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADdKQ8GvZ1yz31NfbN3DFGbLsa7hOGeos',
    appId: '1:929750140649:web:8036695bae1005e427d278',
    messagingSenderId: '929750140649',
    projectId: 'ezfinanz-bp',
    authDomain: 'ezfinanz-bp.firebaseapp.com',
    databaseURL: 'https://ezfinanz-bp.firebaseio.com',
    storageBucket: 'ezfinanz-bp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8lbvfCx2H_10lsQPL_sEFOuKF6Ujt6bw',
    appId: '1:929750140649:android:5f5c6d3c20011d2727d278',
    messagingSenderId: '929750140649',
    projectId: 'ezfinanz-bp',
    databaseURL: 'https://ezfinanz-bp.firebaseio.com',
    storageBucket: 'ezfinanz-bp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4bTzlOLUoEsJEzNigxIEMr-NIwnbtUHk',
    appId: '1:929750140649:ios:88ecb88383c2830327d278',
    messagingSenderId: '929750140649',
    projectId: 'ezfinanz-bp',
    databaseURL: 'https://ezfinanz-bp.firebaseio.com',
    storageBucket: 'ezfinanz-bp.appspot.com',
    androidClientId: '929750140649-428c9i04b2fp5s8pihu8qp0p1b8u5v9v.apps.googleusercontent.com',
    iosClientId: '929750140649-cj8ikiatrubgf0csrd3qm15aj0e974df.apps.googleusercontent.com',
    iosBundleId: 'com.ezfinanz.business.app',
  );
}
